### ISSUE TITLE
First release of quality-summarizer-maven-plugin

### ISSUE THREAD

**Issue by redcatbear** [exasol/quality-summarizer-maven-plugin#4]
## Situation

We need the quality-summarizer on Maven Central. For this we need a release.
Also, I realized that somehow the coverage is not picked up by sonar in this project. That needs to be fixed.

## Acceptance Criteria

- Sonar picks up coverage
- Version 0.1.0 released on Maven Central

**Comment by kaklakariada** [comment]
Closed with #3 and #5
